### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by souwmyaa** [AY1920S2-CS2103T-W16-3/main#283]
- [x] Product release on Github tagged v1.4

- [x] Upload jar file to LumiNUS 
       Name: [CS2103T-W16-3][Study Buddy].jar

- [x] Push the code to GitHub and tag with the version number

- [x] User guide - convert to pdf and submit to LumiNUS (both 2101 and 2103 folder)
       Name: [CS2103T-W16-3][Study Buddy]UG.pdf 

- [x] Developer guide - convert to pdf and submit to LumiNUS (both 2101 and 2103 folder)
      Name: [CS2103T-W16-3][Study Buddy]DG.pdf 

- [x] PPP - convert to pdf and submit to LumiNUS
      Name: [CS2103T-W16-3][Name]PPP.pdf

- [x] Ensure website is auto-published

- [x] UML diagrams - as pdf to LumiNUS
       Name: [CS2103T-W16-3][Name]UML Diagrams.pdf

IMPORTANT:
Constraints on file size- JAR (100 Mb) + all PDF files (15 Mb)
Ensure that executable works on Mac + Windows OS
